- src/api/index.md
options / data  完成,等待校对 @hymRedemption
> Translate Options / data #4

- src/api/index.md
> Revert "Translate Options / data #4"

- src/api/index.md
> translate api/index#global-api

- src/guide/conditional.md
resolve [#12](https://github.com/hayeah/vuejs.org/issues/12)
> trans for guide/conditional

- src/api/index.md
translate api/index#Instance Properties #35 on September 25th
> translate api/index#Instance Properties #35

- src/api/index.md
@egoist @hymRedemption @Mr-Wiredancer @hayeah 来review了
> Trans Options MISC

- src/api/index.md
> translate on api/index#Instance Methods / Data

- src/guide/plugins.md
> 翻译plugins.md

- src/guide/mixins.md
> Trans mixin.md

- README.md
- src/guide/reactivity.md
> translate guide/reactivity

- src/guide/join.md
> Trans join.md

- src/guide/forms.md
> translate guide/form.md

- src/guide/instance.md
对比了 2.0 和 1.0 的文档，差别不大，因此只对 1.0 的翻译做了一些微小的调整，不知这样可否？
> 翻译 guide/instance.md

- src/api/index.md
完成翻译以下三部分：
api/index#Instance Methods/Eevents
api/index#Instance Methods/Lifecycle
api/index#Directives
> 完成翻译三部分：Directives,Lifecycle ,Eevents

- src/guide/components.md
reslove  [#16](https://github.com/hayeah/vuejs.org/issues/16)
> trans for guide/components

- README.md
- src/guide/list.md
> trans for guide-list

- README.md
- src/guide/state-management.md
> 翻译 guide/state-management

- src/guide/custom-directive.md
> translate custom-directive.md

- src/guide/class-and-style.md
> 翻译 class-and-style.md

- src/guide/migration-vuex.md
> 翻译 migration-vuex

- src/guide/render-function.md
> translate guide/render-function

- src/guide/index.md
> finished trans guide/index

- src/guide/ssr.md
终于弄对了。高兴！！！ @Mr-Wiredancer 
resolve #28
> 翻译 guide/ssr.md

- src/guide/transitioning-state.md
这次学会了 `code split`.
resolve #18
> modify guide/transitioning-state.md

- README.md
- src/guide/comparison.md
> finished trans of guide/comparison

- src/guide/events.md
> finished trans of guide/events

- src/guide/migration-vue-router.md
> 翻译 migration-vue-router

- src/guide/single-file-components.md
> 翻译 guide/single-file-components

- src/guide/deployment.md
> 翻译 deployment

- src/guide/transitions.md
> complete translating guide/transitions.md
